### ISSUE TITLE
Shadowed users cause the plugin to fail

### ISSUE THREAD

**Issue by mickyr** [everit-org/jira-timetracker-plugin#221]
This should be applicable to the worklog query plugin as well.

**Criticality is very high** as the reporting part of the plugin simply fails to work. 

Problem: If the jira installation has or had multiple user directories(jira, crowd, ldap etc.) with one or more users being present in multiple directories, the reporting part of the plugin fails(go to reporting and try generating report with any parameters) with the following exception:

```
SEVERE: Servlet.service() for servlet [action] in context with path [/jira] threw exception [com.querydsl.core.QueryException: Caught SQLException for select project.pname as projectName, project.pkey as projectKey, concat(concat(project.pkey, ?), cast(issue.issuenum as char)) as issueKey, issue.summary as issueSummary, issue.id as issueId, issuetype.pname as issueTypeName, issuetype.iconurl as issueTypeIconUrl, issuestatus.pname as issueStatusName, (select case when issueUser.display_name is not null then issueUser.display_name else issue.assignee end
from cwd_user issueUser
left join app_user appUserForIssue
on issueUser.lower_user_name = appUserForIssue.lower_user_name
where appUserForIssue.lower_user_name = issue.assignee) as issueAssignee, issue.timeoriginalestimate as issueOriginalEstimate, issue.timeestimate as issueRemainingEstimate, worklog.worklogbody as worklogBody, worklog.timeworked as worklogTimeWorked, project.description as projectDescription, priority.pname as priorityName, priority.iconurl as priorityIconUrl, (select case when issueUser.display_name is not null then issueUser.display_name else issue.reporter end
from cwd_user issueUser
left join app_user appUserForIssue
on issueUser.lower_user_name = appUserForIssue.lower_user_name
where appUserForIssue.lower_user_name = issue.reporter) as issueReporter, issue.created as issueCreated, issue.updated as issueUpdated, resolution.pname as resolutionName, worklog.startdate as worklogStartDate, worklog.created as worklogCreated, worklog.updated as worklogUpdated, (case when cwd_user.display_name is null then worklog.author else cwd_user.display_name end) as worklogUser
from worklog worklog
join jiraissue issue
on worklog.issueid = issue.id
join project project
on issue.project = project.id
join issuetype issuetype
on issue.issuetype = issuetype.id
join issuestatus issuestatus
on issue.issuestatus = issuestatus.id
join priority priority
on issue.priority = priority.id
left join resolution resolution
on issue.resolution = resolution.id
left join app_user appuser
on appuser.user_key = worklog.author
left join cwd_user cwd_user
on cwd_user.lower_user_name = appuser.lower_user_name
where 1 = 1 and project.id = ? and worklog.author in (select qWorklogAuthor.user_key
from app_user qWorklogAuthor
where qWorklogAuthor.lower_user_name = ?) and worklog.startdate >= ? and worklog.startdate < ?
order by concat(concat(project.pkey, ?), cast(issue.issuenum as char)) asc, worklog.startdate asc
limit ?
offset ?] with root cause
java.sql.SQLException: Subquery returns more than 1 row
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2818)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2157)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2324)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:432)
        at org.everit.jira.reporting.plugin.query.WorklogDetailsReportQueryBuilder$2.call(WorklogDetailsReportQueryBuilder.java:172)
        at org.everit.jira.reporting.plugin.query.WorklogDetailsReportQueryBuilder$2.call(WorklogDetailsReportQueryBuilder.java:156)
        at org.everit.jira.querydsl.support.ri.QuerydslSupportImpl.execute(QuerydslSupportImpl.java:95)
        at org.everit.jira.reporting.plugin.ReportingPluginImpl.getWorklogDetailsReport(ReportingPluginImpl.java:230)
        at org.everit.jira.reporting.plugin.web.ReportingWebAction.createReport(ReportingWebAction.java:201)
        at org.everit.jira.reporting.plugin.web.ReportingWebAction.doExecute(ReportingWebAction.java:303)
```

Probable cause is the subquery:

```
select case when issueUser.display_name is not null then issueUser.display_name else issue.reporter end
from cwd_user issueUser
left join app_user appUserForIssue
on issueUser.lower_user_name = appUserForIssue.lower_user_name
where appUserForIssue.lower_user_name = issue.reporter
```

The following query would return results in an affected jira installation:
`select user_name, count(*) from cwd_user group by user_name having count(*) > 1;`

Also see: Shadowed Users under Atlassian documentation at: https://developer.atlassian.com/jiradev/jira-platform/jira-architecture/database-schema/database-user-and-group-tables

**Comment by balazs-zsoldos** [comment]
Thanks for reporting this!

**Comment by bordatesz** [comment]
Thanks for the detailed report! This will be treated with the highest priority.

**Comment by mickyr** [comment]
Thank you, I really appreciate the quick response. Please let me know if I can help by providing any further details.

**Comment by bordatesz** [comment]
Hello @mickyr!
Thank you for your patience. We made two pre-release tags and uploaded the binaries with the fix. 
- [v3.0.1-RC](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v3.0.1-RC) for JIRA 7.x
- [v2.4.1-RC](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v2.4.1-RC) for JIRA 6.3.x-6.4.x

May I ask you to install and test the right version for your JIRA, and give me a feedback?

**Comment by mickyr** [comment]
Thanks for the quick resolution. I will install and test the pre-release tags early next week in our environment.

**Comment by bordatesz** [comment]
Hi @mickyr!

Did you manage to try the fixes?

**Comment by bordatesz** [comment]
We released 3.0.1 and 2.4.1 versions on the Atlassian Marketplace with the fix, so I'm closing this Issue. If there is any problem in the future, feel free to reopen it!

**Comment by mickyr** [comment]
Apologies for the late response. I know that this is already closed but I just wanted to inform that I did test and can confirm that your fix works in our environment. Thanks a lot for your help and for maintaining this excellent plugin. You guys are more responsive than a lot of paid plugin vendors.

**Comment by bordatesz** [comment]
No problem. Glad to hear it worked! :)
