### ISSUE TITLE
500 when generating reports

### ISSUE THREAD

**Issue by mcassidygamma** [everit-org/jira-timetracker-plugin#246]
I've recently installed this plugin on our test instance of Jira to try it out.

The time logging aspect works fine, but when attempting to generate a report (clicking time tracker, choosing reporting), selecting projects ect, and pressing "create report" the resulting page is a 500 error. 

I'm using Jira Software v7.1.7#71011-sha1:2526d7c

The following is from the log file:

```
2016-06-06 15:03:10,881 http-nio-80-exec-17 ERROR      [o.a.c.c.C.[.[localhost].[/].[action]] Servlet.service() for servlet [action] in context with path [] threw exception [com.querydsl.core.QueryException: Caught SQLException for select * from (
      select (case when exists (select top (?) cwdUserExists.display_name
    from jiraschema.cwd_user cwdUserExists
    left join jiraschema.app_user appUserExists
    on appUserExists.lower_user_name = cwdUserExists.lower_user_name
    left join jiraschema.cwd_directory cwdDirectoryExists
    on cwdUserExists.directory_id = cwdDirectoryExists.id
    where appUserExists.user_key = worklog.author
    order by cwdDirectoryExists.directory_position asc) then (select top (?) case when issueUser.display_name is not null then issueUser.display_name else worklog.author end
    from jiraschema.cwd_user issueUser
    left join jiraschema.app_user appUserForIssue
    on appUserForIssue.lower_user_name = issueUser.lower_user_name
    left join jiraschema.cwd_directory cwdDirectoryForIssue
    on issueUser.directory_id = cwdDirectoryForIssue.id
    where appUserForIssue.user_key = worklog.author
    order by cwdDirectoryForIssue.directory_position asc) else worklog.author end) as userDisplayName, sum(worklog.timeworked) as workloggedTimeSum, row_number() over (order by userDisplayName asc) as rn
    from jiraschema.worklog worklog
    join jiraschema.jiraissue issue
    on worklog.issueid = issue.id
    join jiraschema.project project
    on issue.project = project.id
    join jiraschema.issuetype issuetype
    on issue.issuetype = issuetype.id
    join jiraschema.issuestatus issuestatus
    on issue.issuestatus = issuestatus.id
    join jiraschema.priority priority
    on issue.priority = priority.id
    left join jiraschema.resolution resolution
    on issue.resolution = resolution.id
    where 1 = 1 and (project.id in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)) and worklog.startdate >= ? and worklog.startdate < ?
    group by worklog.author) a where rn > ? and rn <= ? order by rn] with root cause
java.sql.SQLException: Invalid column name 'userDisplayName'.
    at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
    at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
    at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
    at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
    at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQLQuery(JtdsStatement.java:505)
    at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.executeQuery(JtdsPreparedStatement.java:1029)
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
    at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:432)
    at org.everit.jira.reporting.plugin.query.UserSummaryReportQueryBuilder$2.call(UserSummaryReportQueryBuilder.java:105)
    at org.everit.jira.reporting.plugin.query.UserSummaryReportQueryBuilder$2.call(UserSummaryReportQueryBuilder.java:85)
    at org.everit.jira.querydsl.support.ri.QuerydslSupportImpl.execute(QuerydslSupportImpl.java:95)
    at org.everit.jira.reporting.plugin.ReportingPluginImpl.getUserSummaryReport(ReportingPluginImpl.java:201)
    at org.everit.jira.reporting.plugin.web.ReportingWebAction.createReport(ReportingWebAction.java:209)
    at org.everit.jira.reporting.plugin.web.ReportingWebAction.doExecute(ReportingWebAction.java:302)
    ... 1 filtered
    at com.atlassian.jira.action.JiraActionSupport.execute(JiraActionSupport.java:63)
    ... 7 filtered
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    ... 50 filtered
    at com.atlassian.greenhopper.jira.filters.ClassicBoardRouter.doFilter(ClassicBoardRouter.java:59)
    ... 62 filtered
    at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:70)
    ... 89 filtered
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by bordatesz** [comment]
Hello @mcassidygamma!

We'll look into it! Can you give me some further technical information as:
- Which Timetracker version did you use?
- What kind of database are you using with the test instance?

**Comment by tbitowt** [comment]
Hi,
I have same problem.

I'm using:

- hsql database (HSQL Database Engine Driver 1.8.0)
- TimeTracker versio 2.4.1

**Comment by mcassidygamma** [comment]
I'm using 3.0.1 with Microsoft SQL server 2012

**Comment by bordatesz** [comment]
@mcassidygamma 
Thank you. We are working on it.

**Comment by bordatesz** [comment]
Hello @mcassidygamma!
Thank you for your patience. We made a pre-release tag and uploaded the binaries with the fix.
- [v3.1.0-RC for JIRA 7.x](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v3.1.0-RC)

May I ask you to install and test this version and give me a feedback?

**Comment by bordatesz** [comment]
Hi @mcassidygamma!
Did you manage to try the fixes?

**Comment by mcassidygamma** [comment]
Hi @bordatesz 
I've tried it out this morning and it looks good. I can generate reports successfully now.
Thanks!

**Comment by bordatesz** [comment]
Glad to hear it worked! :) The official fix be released in a few days on the Atlassian Marketplace.
