### ISSUE TITLE
Recent permission change now throws a 500 when trying to reach the permission configuration.

### ISSUE THREAD

**Issue by HFG-InfoTech** [everit-org/jira-timetracker-plugin#511]
[c.a.j.web.servlet.InternalServerErrorServlet] {errorId=06c3e5bb-209d-4803-9a27-075134728499, interpretedMsg=, cause=java.lang.ClassCastException: org.everit.jira.timetracker.plugin.dto.UserGroupPickerDisplayDTO cannot be cast to java.lang.Comparable, stacktrace=java.lang.ClassCastException: org.everit.jira.timetracker.plugin.dto.UserGroupPickerDisplayDTO cannot be cast to java.lang.Comparable
    	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) [?:1.8.0_202]
    	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) [?:1.8.0_202]
    	at java.util.TimSort.sort(TimSort.java:220) [?:1.8.0_202]
    	at java.util.Arrays.sort(Arrays.java:1512) [?:1.8.0_202]
    	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348) [?:1.8.0_202]
    	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) [?:1.8.0_202]
    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_202]
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_202]
    	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_202]
    	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_202]
    	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_202]
    	at org.everit.jira.timetracker.plugin.web.PermissionSettingsWebAction.loadPluginSettingAndParseResult(PermissionSettingsWebAction.java:243) [?:?]
    	at org.everit.jira.timetracker.plugin.web.PermissionSettingsWebAction.doDefault(PermissionSettingsWebAction.java:116) [?:?]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [?:1.8.0_202]
...

**Comment by attila-kiss-it** [comment]
Hello HFG-InfoTech,

We just released a newer (4.8.0) version of Timetracker. After updating to it, you should no longer experience this issue.

Please let us know how it goes.
Thank you!

Regards,
Attila
